// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Authprovider from "@/context/Authprovider";
import { ThemeProvider } from "@/components/theme-provider";
import Nav from "@/components/nav/Nav";
import ReduxProvider from "@/context/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        <Authprovider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >           
          <ReduxProvider> 
                {children}
          </ReduxProvider> 
            <Toaster />
          </ThemeProvider>
        </Authprovider>
      </body>
    </html>
  );
}
